products/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


from .views import ProductDetailView, ProductListView,VariationListView, CategoryDetailView, CategoryListView

urlpatterns = [
    # Examples:
    # url(r'^$', 'newsletter.views.home', name='home'),
    #url(r'^$', 'products.views.product_list', name='products'),
    url(r'^$', ProductListView.as_view(), name='products'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    url(r'^category/(?P<slug>\w+)/$', CategoryDetailView.as_view(), name='category_detail'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),
    #url(r'^(?P<id>\d+)', 'products.views.product_detail_view_func', name='product_detail_function'),
]

orders/models.py
from decimal import Decimal
import braintree

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save

from carts.models import Cart, CartItem
from products.models import Variation

# Create your models here.



braintree.Configuration.configure(braintree.Environment.Sandbox,
    merchant_id = settings.BRAINTREE_MERCHAND_ID,
    public_key = settings.BRAINTREE_PUBLIC,
    private_key = settings.BRAINTREE_PRIVATE
)

class UserCheckout(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True)
    email = models.EmailField(unique=True)
    braintree_id = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.email

    @property
    def get_braintree_id(self):
        instance = self
        if not instance.braintree_id:
            result = braintree.Customer.create({
                "email": instance.email,
            })
            if result.is_success:
                instance.braintree_id = result.customer.id
                instance.save()
        return instance.braintree_id

    def get_client_token(self):
        customer_id = self.get_braintree_id
        if customer_id:
            client_token = braintree.ClientToken.generate({
                "customer_id": customer_id,
            })
            return client_token
        return None

def update_braintree_id(sender, instance, *args, **kwargs):
	if not instance.braintree_id:
		instance.get_braintree_id

post_save.connect(update_braintree_id, sender=UserCheckout)


ADDRESS_TYPE = (
    ('billing', 'Billing'),
    ('shipping', 'Shipping')
)

class UserAdress(models.Model):
    user = models.ForeignKey(UserCheckout)
    type = models.CharField(max_length=120, choices=ADDRESS_TYPE, default="Billing")
    street = models.CharField(max_length=120)
    city = models.CharField(max_length=120)
    state = models.CharField(max_length=120)
    zipcode = models.CharField(max_length=120)

    def __str__(self):
        return self.street

    def get_addresses(self):
        return "%s, %s, %s, %s" %(self.street, self.city, self.state, self.zipcode)


ORDER_STATUS_CHOICES = (
    ("created","Created"),
    ("paid", "Paid"),
    ("shippend", "Shipped"),
    ('refunded', 'Refunded'),
)


class Order(models.Model):
    status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='created')
    cart = models.ForeignKey(Cart)
    user = models.ForeignKey(UserCheckout,null=True)
    billing_address  = models.ForeignKey(UserAdress, related_name='billing_address', null=True)
    shipping_address  = models.ForeignKey(UserAdress, related_name='shipping_address', null=True)
    shipping_total_price = models.DecimalField(max_digits=50,decimal_places=2 , default=5.99)
    order_total = models.DecimalField(max_digits=50,decimal_places=2)
    order_id = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return str(self.cart.id)

    class Meta:
         ordering = ['-id']

    def get_absolute_url(self):
        return reverse("order_detail", kwargs={"pk":self.pk})

    class Meta:
        ordering  =  ['-id']

    def mark_completed(self, order_id=None):
        self.status = "paid"
        if order_id and not self.order_id:
            self.order_id = order_id
        self.save()


def order_pre_save(sender, instance, *args, **kwargs):
    shipping_total_price = instance.shipping_total_price
    cart_total = instance.cart.total
    order_total = round(Decimal(shipping_total_price) +  Decimal(cart_total ), 2)
    instance.order_total = order_total
pre_save.connect(order_pre_save, sender=Order)

orders/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserAdress

User =  get_user_model()

class GuestCheckoutForm(forms.Form):
    email = forms.EmailField()
    email2 = forms.EmailField(label='Verify Email')

    def clean_email2(self):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")

        if email == email2:
            user_exists = User.objects.filter(email=email).count()
            if user_exists != 0:
                raise forms.ValidationError("User exist please login")
            return email2
        else:
            raise forms.ValidationError("Please confirm emails are the same")

class AddressForm(forms.Form):
    billing_address = forms.ModelChoiceField(
        queryset=UserAdress.objects.filter(type="billing"),
        empty_label = None
        )
    shipping_address = forms.ModelChoiceField(
        queryset=UserAdress.objects.filter(type="shipping"),
        empty_label = None,
        )


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAdress
        fields = [
            'street',
            'city',
            'state',
            'zipcode',
            'type',
        ]

orders/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, CreateView
from django.views.generic.list import ListView

from .forms import AddressForm, UserAddressForm
from .mixins import CartOrderMixin, LoginRequiredMixin
from .models import UserAdress, UserCheckout, Order


class OrderDetailView( DetailView):
    model = Order

    def dispatch(self, request, *args, **kwargs):
        try:
            user_check_id = self.request.session.get("user_checkout_id")
            user_checkout = UserCheckout.objects.get(id=user_check_id)
        except UserCheckout.DoesNotExist:
            user_checkout = UserCheckout.objects.get(user=request.user)
        except:
            user_checkout = None
        obj = self.get_object()
        if obj.user == user_checkout and user_checkout is not None:
            return super(OrderDetailView, self).dispatch(request, *args, **kwargs)
        else:
            raise Http404


class OrdersList(LoginRequiredMixin, ListView):
    queryset = Order.objects.all()
    paginate_by = 12

    def get_queryset(self):
        try:
            user_check_id = self.request.user.id
            #user_checkout = UserCheckout.objects.get(id=user_check_id)
            #return super(OrderList, self).get_queryset().filter(user=user_checkout)
        except user_checkout_id.DoesNotExist:
            user_checkout_id = None
        return super(OrdersList, self).get_queryset().filter(user__user=user_check_id)





# Create your views here.
class UserAdressCreateView(CreateView):
    form_class = UserAddressForm
    template_name = 'forms.html'
    success_url = "/checkout/address/"

    def get_checkout_user(self):
        user_checkout_id = self.request.session.get("user_checkout_id")
        user_checkout = UserCheckout.objects.get(id=user_checkout_id)
        return user_checkout

    def form_valid(self, form, *args, **kwargs):
        form.instance.user = self.get_checkout_user()
        return super(UserAdressCreateView, self).form_valid(form, *args, **kwargs)


class AddressSelectFormView(CartOrderMixin, FormView):
    form_class = AddressForm
    template_name = 'orders/address_select.html'

    def dispatch(self, *args, **kwargs):
        b_address, s_address = self.get_addresses()
        if b_address.count() == 0:
            messages.success(self.request, "Please add a billing address ")
            return redirect("user_address_create")
        elif s_address.count() == 0:
            messages.success(self.request, "Please add a shipping address  ")
            return redirect("user_address_create")
        else:
            return super(AddressSelectFormView, self).dispatch(*args, **kwargs)

    def get_addresses(self, *args, **kwargs):
        user_checkout_id = self.request.session.get("user_checkout_id")
        user_checkout = UserCheckout.objects.get(id=user_checkout_id)
        b_address = UserAdress.objects.filter(
            user= user_checkout,
            type='billing',
            )
        s_address = UserAdress.objects.filter(
            user= user_checkout,
            type='shipping',
            )
        return b_address, s_address


    def get_form(self, *args, **kwargs):
        form = super(AddressSelectFormView, self).get_form( *args, **kwargs)
        b_address, s_address = self.get_addresses()

        form.fields["billing_address"].queryset = b_address
        form.fields["shipping_address"].queryset = s_address
        return form

    def form_valid(self, form, *args, **kwargs):
        billing_address = form.cleaned_data["billing_address"]
        shipping_address = form.cleaned_data["shipping_address"]

        order = self.get_order()
        order.billing_address = billing_address
        order.shipping_address = shipping_address
        order.save()
        return  super(AddressSelectFormView, self).form_valid(form, *args, **kwargs)

    def get_success_url(self, *args, **kwargs):
        return "/checkout/"

orders/templates/orders/address_select.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<style media="screen">
  {% block style %}
  .box{

     padding: 10px;
     background-color: #ccc;
     box-shadow: 2px 2px 2px  #888888;
     color:#fff;
  }
  .button{
    width:200px;
    margin-top: 10px;
    display: block;
    margin: 0 auto;

}

.corpo{
  padding:30px;
  border:1px  #ccc solid;
}

  {% endblock style %}
</style>

<div class="container" style="height: 100%;">
  <div class="row" style="height: 100%" >
    <div class="col-sm-8 col-sm-offset-2 box">
      <h1 class="text-center">Delivery address</h1>
    </div>
    <div class="col-sm-8 col-sm-offset-2 corpo"style="height: 100%;">
    <form  method="POST" action=''>
      {% csrf_token %}
      {{form|crispy}}
      <br>
      <input class="btn btn-success button" type="submit" value="select" />
      <br>
      <a class="btn  btn-default button" href='{% url "user_address_create" %}'>Add New</a>
    </form>
  </div>
</div>
</div>
{% endblock %}

orders/templates/orders/order_detail.html
{% extends "dashboard/index.html" %}


  {% block accounts_content  %}
    <div class="col-md-8 col-md-offset-2">
      {% include "orders/order_summary_short.html" with order=order%}
    </div>
  {% endblock accounts_content %}

orders/templates/orders/order_list.html
{% extends "dashboard/index.html" %}

{% block accounts_content%}
{% if object_list|length <= 0 %}
<div class="text-center">
  <p>You do not currently have orders. </p>
</div>

{% else %}

<div class="col-sm-8 col-md-offset-2">
<h1 class="text-center">My orders</h1>
<table class="table">
  <thead>
    <tr>
      <th>ORDER</th>
      <th>ITEMS</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
      <tr>
        <td><a href="{{ object.get_absolute_url }}">View  #{% if object.order_id%}{{ object.order_id}} {% else %}{{object.id}} {% endif %}</a></td>
        <td>Item quantity: {{object.cart.items.count }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
<div class="row">
    <nav>
      <ul class="pagination">
          {% for page in paginator.page_range %}
            <li>
              <a href="?page={{ page }}"> {{ page }}</a>
            </li>
          {% endfor %}
      </ul>
    </nav>
</div>
</div>
{% endblock accounts_content%}

orders/templates/orders/order_summary_short.html
<style>


</style>

<dl class="dl-horizontal ">
  <dt><h1><b>ORDER</b></h1></dt>
  <dd><h1>{{order.order_id}}</h1></dd>
  <dt>STATUS</dt>
  <dd>{{object.get_status_display}}</dd>
  <dt>ITEM{% if order.cart.items.count > 1 %}S{% endif %}</dt>
  <dd>{% for i in order.cart.cartitem_set.all %}<b>{{i.item.get_title}}</b>{% endfor %}</dd>
  <dt>TAX</dt>
  <dd>{{ order.cart.tax_total}}</dd>
  <dt>SUBTOTAL</td>
  <dd>{{ order.cart.subtotal}}</dd>
  <dt>SHIPPING</dt>
  <dd>{{ order.shipping_total_price}}</dd>
  <dt>ORDER TOTAL</dt>
  <dd>{{ order.order_total}}</dd>
</dl>

<dl class="dl-horizontal">
  <dt>BILLING</dt>
  <dd><td>{{order.billing_address.get_addresses}}</td></dd>
  <dt>SHIPPING</dt>
  <dd>{{order.shipping_address.get_addresses}}</dd>
</dl>

orders/templates/orders/useradress_confirm_delete.html
      <form action="{% url 'accounts_users:address_delete' pk=object.pk %}" method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
          <input type="submit" value="Confirm" />
      </form>