products/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


from .views import ProductDetailView, ProductListView,VariationListView, CategoryDetailView, CategoryListView

urlpatterns = [
    # Examples:
    # url(r'^$', 'newsletter.views.home', name='home'),
    #url(r'^$', 'products.views.product_list', name='products'),
    url(r'^$', ProductListView.as_view(), name='products'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product_detail'),
    url(r'^category/(?P<slug>\w+)/$', CategoryDetailView.as_view(), name='category_detail'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),
    #url(r'^(?P<id>\d+)', 'products.views.product_detail_view_func', name='product_detail_function'),
]

orders/models.py
from decimal import Decimal
import braintree

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save, post_save

from carts.models import Cart, CartItem
from products.models import Variation

# Create your models here.



braintree.Configuration.configure(braintree.Environment.Sandbox,
    merchant_id = settings.BRAINTREE_MERCHAND_ID,
    public_key = settings.BRAINTREE_PUBLIC,
    private_key = settings.BRAINTREE_PRIVATE
)

class UserCheckout(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True)
    email = models.EmailField(unique=True)
    braintree_id = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.email

    @property
    def get_braintree_id(self):
        instance = self
        if not instance.braintree_id:
            result = braintree.Customer.create({
                "email": instance.email,
            })
            if result.is_success:
                instance.braintree_id = result.customer.id
                instance.save()
        return instance.braintree_id

    def get_client_token(self):
        customer_id = self.get_braintree_id
        if customer_id:
            client_token = braintree.ClientToken.generate({
                "customer_id": customer_id,
            })
            return client_token
        return None

def update_braintree_id(sender, instance, *args, **kwargs):
	if not instance.braintree_id:
		instance.get_braintree_id

post_save.connect(update_braintree_id, sender=UserCheckout)


ADDRESS_TYPE = (
    ('billing', 'Billing'),
    ('shipping', 'Shipping')
)

class UserAdress(models.Model):
    user = models.ForeignKey(UserCheckout)
    type = models.CharField(max_length=120, choices=ADDRESS_TYPE, default="Billing")
    street = models.CharField(max_length=120)
    city = models.CharField(max_length=120)
    state = models.CharField(max_length=120)
    zipcode = models.CharField(max_length=120)

    def __str__(self):
        return self.street

    def get_addresses(self):
        return "%s, %s, %s, %s" %(self.street, self.city, self.state, self.zipcode)


ORDER_STATUS_CHOICES = (
    ("created","Created"),
    ("paid", "Paid"),
    ("shippend", "Shipped"),
    ('refunded', 'Refunded'),
)


class Order(models.Model):
    status = models.CharField(max_length=120, choices=ORDER_STATUS_CHOICES, default='created')
    cart = models.ForeignKey(Cart)
    user = models.ForeignKey(UserCheckout,null=True)
    billing_address  = models.ForeignKey(UserAdress, related_name='billing_address', null=True)
    shipping_address  = models.ForeignKey(UserAdress, related_name='shipping_address', null=True)
    shipping_total_price = models.DecimalField(max_digits=50,decimal_places=2 , default=5.99)
    order_total = models.DecimalField(max_digits=50,decimal_places=2)
    order_id = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return str(self.cart.id)

    class Meta:
         ordering = ['-id']

    def get_absolute_url(self):
        return reverse("order_detail", kwargs={"pk":self.pk})

    class Meta:
        ordering  =  ['-id']

    def mark_completed(self, order_id=None):
        self.status = "paid"
        if order_id and not self.order_id:
            self.order_id = order_id
        self.save()


def order_pre_save(sender, instance, *args, **kwargs):
    shipping_total_price = instance.shipping_total_price
    cart_total = instance.cart.total
    order_total = round(Decimal(shipping_total_price) +  Decimal(cart_total ), 2)
    instance.order_total = order_total
pre_save.connect(order_pre_save, sender=Order)

templates/dashboard/addres_add.html
{% extends "dashboard/index.html" %}

{% load crispy_forms_tags%}

{% block accounts_content%}
<div class="page-header">
  <h1 class="text-center">Address</h1>
</div>
<div class="col-sm-8 col-sm-offset-2">
  <form method='POST' action=''>{% csrf_token %}
  {{ form|crispy }}
  <input class='btn btn-success button' type='submit' value='Submit'/>
  </form>
</div>
{% endblock accounts_content%}

templates/dashboard/address_edit.html
{% extends "dashboard/index.html" %}

{% load crispy_forms_tags%}

{% block accounts_content%}

{% if object.type == "shipping" %}
<div class="page-header">
  <h1 class="text-center">Shipping address</h1>
</div>
{% else %}
<div class="page-header">
  <h1  class="text-center">Billing address</h1>
</div>
{% endif %}

<div class="col-sm-8 col-sm-offset-2">
  <form action="" method="post" >{% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Update" />
  </form>
</div>

{% endblock accounts_content%}

templates/dashboard/address_list.html
{% extends "dashboard/index.html" %}

{% load crispy_forms_tags%}

{% block accounts_content%}

<script type="text/javascript">
  {% block jquery %}


  {% endblock jquery %}
</script>

<style media="screen">
  {% block style %}
      .list-group-item ul{
        text-decoration: none;
        list-style-type: none;
      }

      #address-box  a{
        text-decoration: none;
      }

      #address-box  a i{
        text-decoration: none;
      }

      #address-box  a i:hover{
        color:#a9a9a9;
        display: block;
      }
  {% endblock style %}
</style>

{% if object_list.count <= 0 %}
  <h1 class="text-center">No address added </h1>
{% else %}
<div class="page-header">
<h1 class="text-center">Address</h1>
</div>

  {% for object in object_list  %}
  <div class="col-sm-4 {{ col_class_set }}" >
  <div class="list-group" id="address-box">
    <div class="list-group-item active">
      <h2 class="list-group-item-heading">{{object.type}}</h2>
      <a class="pull-right"  data-toggle="modal" data-target="#{{object.pk}}"  style="color:white; position:relative; top:-20px; "><i class="fa fa-trash fa-2x" aria-hidden="true"></i></a>
      <a class="pull-right" style="color:white; position:relative; top:-20px; left:-10px;" href="{% url 'accounts_users:address_edit' pk=object.pk %}"><i class="fa fa-pencil fa-2x" aria-hidden="true"></i></a>
    </div>
    <div class="list-group-item">
       <ul>
         <li><b>{{object.street}}</b></li>
         <li>{{object.city}}</li>
         <li>{{object.state}}</li>
         <li>{{object.zipcode}}</li>
       </ul>
    </div>
  </div>
  {% if forloop.counter|divisibleby:3 %}
    </div><div class="row">
  {% endif %}
  </div>
  <div class="modal fade" id="{{object.pk}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form action="{% url 'accounts_users:address_delete' pk=object.pk %}" method="post">{% csrf_token %}
        <div class="modal-header">
          <h2>Delete {{object.type}} Address</h2>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete "{{ object }}"?</p>
        </div>
        <div class="modal-footer">
          <a href="{% url 'accounts_users:address_list' %}" class="btn btn-danger">Cancel</a>
          <input class="btn btn-success" type="submit" value="Confirm" />
          <input type="hidden" name="next" value="{% url 'accounts_users:address_list' %}" />
        </div>
        </form>
      </div>
    </div>
  </div>

  {% endfor %}
{% endif %}

<!-- new button <a class="btn btn-success" href="{% url 'accounts_users:address_add' %}">Add address<a/>-->

{% endblock accounts_content%}

templates/dashboard/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid display-table ">
    <div class="row  display-table-row">

        <div class="col-md-2 col-sm-1 display-table-cell valign-top " id="side-menu">
            <h1 class="hidden-xs hidden-sm">Dashboard</h1>

            <li class="link">
              <a href="{% url 'order_list' %}" >
                <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
                 <span class="hidden-xs">Orders</span>
              </a>
            </li>


            <li class="link">
              <a href="#collapse-comments" data-toggle="collapse" aria-controls="collapse-post">
                <i class="fa fa-comments" aria-hidden="true"></i>
                <span class="hidden-xs">Comments</span>
              </a>
              <ul class="collapse collapseable" id="collapse-comments">
                <li><a href="#">Test</a></li>
                <li><a href="#">Test</a></li>
              </ul>
            </li>

            <li class="link settings-btn">
              <a href="#collapse-conf" data-toggle="collapse" aria-controls="collapse-post">
                <i class="fa fa-cog" aria-hidden="true"></i>
                <span class="hidden-xs">Settings</span>
              </a>
              <ul class="collapse collapseable" id="collapse-conf">
                <li><a href="{% url 'accounts_users:address_list' %}">Address</a></li>
                <li><a href="#">Test</a></li>
              </ul>
            </li>
        </div>

        <div class="col-md-10 display-table-cell valign-top">
          <div class="row">
            <header id="nav-header" class="clearfix">
        

              <!--<div class="col-md-7">
                <ul class="pull-right">
                  <li id="welcome" class="hidden-xs ">Welcome to your administration area</li>
                  <li class="fixed-width">
                    <a href="#">
                      <i class="fa fa-bell-o" aria-hidden="true"></i>
                      <span class="label label-warning">3</span>
                    </a>
                  </li>

                  <li  class="fixed-width">
                    <a href="#">
                      <i class="fa fa-envelope-o" aria-hidden="true"></i>
                      <span class="label label-info">3</span>
                    </a>
                  </li>

                  <li>
                    <a href="#">
                      <i class="fa fa-sign-out" aria-hidden="true"></i>
                      log out
                    </a>
                  </li>
                </ul>
              </div>-->
            </header>
          </div>

          {% block accounts_content  %}

          {% endblock accounts_content %}

          <!--<div class="row">
            <footer id="admin-footer" class="clearfix">
              <div class="pull-left"><b>Copyright</b>&copy;2017</div>
              <div class="pull-right">admin system</div>
            </footer>
          </div>-->


        </div>
    </div>
  </div>
{% endblock content %}